### ISSUE TITLE
Collection of frontend bugs with lower priority - TODO: Create / add to issues

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#97]
Create issues for following bugs: 

- [x] Assess --> "nextpage button" throws TypeError
- [x] Assess --> Today filter funktioniert nicht 
- [x] Assess -->  total items: 2 / displayed items: 0 (see screenshot)
-----------------------
- [x] report types can no tbe edited:  error im backend: `TypeError: Attribute.__init__() got an unexpected keyword argument 'attribute_enums'`
- [x] when selecting items in analyze table error occurs (but delete is possible) `"ReferenceError: state is not defined" delete `
- [x] Permissions in roles view are not displayed
- [x] set roles and permissions to users not working
- [x] Addresses not loaded in oganization
-----------------------
- [x]  Expand toolbar as default
-----------------------
- [x]  Handle expired token 
- [x] before first login following error message appears `GET http://localhost:5000/api/v1/users/my-profile 401 (UNAUTHORIZED)`
-----------------------
- [x] relevance settings in story detail view is not reactive 
- [x] should relevance settings also be displayed in list view? 
- [x]  in StoryMetaInfo / Story detail view: tags can be selected multiple times --> filter contains same tags multiple times  
- [x]  Assess / "remove from story" --> if multiple stories are combined, stories can be removed but story group is not updated reactively  
- [x] Assess -> number of total assets not reactive 
- [x] refactor setting of y2Max value in WeekChart 
- [x] `dateChips.vue:26 [Vue warn]: defineEmits() is a compiler-hint helper that is only usable inside <script setup> of a single file component. Its arguments should be compiled away and passing it at runtime has no effect.`
-----------------------
 - [x] AnalyzeView  -> set incomplete filter 
-----------------------
- [x] Reports -> enable RICH_TEXT & Attribute CVSS display
- [x] Reports -> Adapt color scheme from "Side-by-side" and "Completed"
- [x] Make it a Form --> check for rules on save
- [x] Analyze view --> when selecting multiple reports (for delete) and then filtering by e.g. week, all reports are still selected
- [x] Report VIew --> news items not displayed correctly (Relevance, full text etc) see screenshots in comment 
-----------------------
- [x] config/reportitems/types --> should edit be possible?
- [x] config/organization (Administration) -> add, edit & delete not working --> required fields not displayed
- [x]  config/roles -> roles can't be created or edited with permissions set
- [x] config/collectors/groups --> delete could not be tested as submit not working 
- [x] Report Types: config success message --> "successfully deleted undefined" warning 
- [x] config/publishers/presets --> delete item not possible 
- [x] config/wordlists not displaying anything --> WordListView:57: caught (in promise) ReferenceError: storeToRefs is not defined

**Comment by ewoiset** [comment]
![Image](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/7a104a82-be60-494f-9258-05c2b17146e6)

**Comment by ewoiset** [comment]
![Screenshot from 2023-06-21 09-43-57](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/75f1d562-39b3-45b9-afc2-ed0bf74d85cb)
![Screenshot from 2023-06-21 09-43-44](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/afe3e14f-1276-43f2-85b9-ea39965a6038)

**Comment by ewoiset** [comment]
![Screenshot from 2023-06-21 14-32-01](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/c8fdacfa-1756-43bd-9af0-f1bc048fa0a1)

**Comment by b3n4kh** [comment]
> ![Screenshot from 2023-06-21 14-32-01](https://user-images.githubusercontent.com/88492381/247554820-c8fdacfa-1756-43bd-9af0-f1bc048fa0a1.png)

The "bug" here is that it is allowed to have an offset greater then the number of "total_items". 

The number of "total_items" however is not known until the query is completed. So the only way to solve this would be something in the backend that if an offset is set and no results are yielded tries the same query without the offset.

I am unsure of how valid this usecase is, maybe an approach to show a button to "clear filters" if 0 results are returned?
